import Head from 'next/head'



export default function Home() {
  function toggle() {
    document.documentElement.classList.toggle("animated")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app">
        <div id="product-image">
          <button id="btn-360" onClick={toggle}>
            <img
              src="./assets/360.svg"
              alt="clique nesse botao para animar o sofa"
            />
          </button>
          <button id="btn-close" onClick={toggle}>
            <img src="./assets/close.svg" alt="parar de animar o sofa" />
          </button>

          <img id="static" src="./assets/sofa.jpg" alt="sofa" />
          <img id="animated" src="./assets/sofa.gif" alt="sofa animado" />
        </div>

        <div id="product-details">
          <h4>CÓDIGO: 42404</h4>
          <h1>Sofá Margot II - Rosé</h1>
          <p>R$ 4.000</p>
          <button>ADICIONAR À CESTA</button>
        </div>
      </div>
    </>
  )
}
