import Head from 'next/head'
import sofa from '../assets/sofa.jpg'
import Image from 'next/image'
import image360 from '../assets/360.svg'
import close from '../assets/close.svg'
import sofaGif from '../assets/sofa.gif'

export default function Home() {
  function toggle() {
    document.documentElement.classList.toggle("animated")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app">
        <div id="product-image">
          <button id="btn-360" onClick={toggle}>
            <Image
              src={image360}
              alt="clique nesse botao para animar o sofa"
            />
          </button>
          <button id="btn-close" onClick={toggle}>
            <Image src={close} alt="parar de animar o sofa" />
          </button>

          <Image id="static" src={sofa} alt="sofa" />
          <Image id="animated" src={sofaGif} alt="sofa animado" />
        </div>

        <div id="product-details">
          <h4>CÓDIGO: 42404</h4>
          <h1>Sofá Margot II - Rosé</h1>
          <p>R$ 4.000</p>
          <button>ADICIONAR À CESTA</button>
        </div>
      </div>
    </>
  )
}
